### ISSUE TITLE
Migrate CI build to GitHub actions

### ISSUE THREAD

**Issue by treeder** [gochain/gochain#466]
```[tasklist]
### Tasks
- [x] Get build working
- [x] Push images to GitHub container registry
- [ ] https://github.com/gochain/gochain/issues/483
- [x] Update docs and docker compose files
```

**Comment by treeder** [comment]
Versioning doesn't work because of this issue: https://github.com/orgs/community/discussions/13836
